[build]
  command = "npm ci && node node_modules/vite/bin/vite.js build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NPM_CONFIG_PRODUCTION = "false"  

[functions]
  node_bundler = "esbuild"

# Redirects para SPA (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirects para as tuas APIs (Netlify Functions)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/fatura"
  to = "/.netlify/functions/api/fatura"
  status = 200